name: sparrow-extensions
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - ninja
  - cxx-compiler
  # Libraries dependencies
  - simdjson
  - sparrow-devel >=1.4.0
  # Testing dependencies
  - doctest
  # Documentation dependencies
  - doxygen
  - graphviz
